name: "oci"
version: "0.3.4"
description: |-
  Get packaged Charts from OCI, support both downloader & proxy mode
command: "bin/helm-oci"
downloaders:
  - command: "bin/helm-oci"
    protocols:
      - "oci+login"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
