name: PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        ruby: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install Deps (Linux)
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev automake -y
      if: startsWith(matrix.os , 'ubuntu')
    - name: Install Deps (macos)
      run: brew install automake
      if: startsWith(matrix.os , 'macos')
    - name: build 
      run: rake build
